site_name: The Radon Programming Language
site_description: "The Radon Programming Language"
site_author: "Md. Almas Ali"
site_url: "https://radon-project.github.io/"
repo_url: "https://github.com/radon-project/radon"
repo_name: "radon-project/radon"
use_directory_urls: false

theme:
  name: material
  custom_dir: "docs/theme"

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indego
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indego
      accent: amber
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

  features:
    - content.tabs.link
    - content.code.select
    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight
    - navigation.path
    - navigation.top

  logo: "assets/images/radon.png"
  favicon: "assets/images/favicon.ico"

extra:
  analytics:
    provider: google
    property: G-KJJTKMQBZE

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/radon-project

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/md-almasali/

    - icon: fontawesome/solid/globe
      link: https://almasali.net

  meta:
    - name: description
      content: "Radon a programming language"
    - name: keywords
      content: "radon, radon programming language, radon language, radon-lang"
    - name: author
      content: "Md. Almas Ali"
    - name: og:title
      content: "Radon"
    - name: og:description
      content: "Radon a programming language"
    - name: og:image
      content: "assets/images/radon.png"
    - name: og:url
      content: "https://radon-project.github.io/"
    - name: og:site_name
      content: "Radon"
    - name: og:locale
      content: "en_US"
    - name: og:type
      content: "website"
    - name: twitter:card
      content: "summary"
    - name: twitter:site
      content: "@radon-project"
    - name: twitter:creator
      content: "@almasali22"
    - name: twitter:title
      content: "Radon"
    - name: twitter:description
      content: "The Radon Programming Language"
    - name: twitter:image
      content: "assets/images/radon.png"
    - name: twitter:image:alt
      content: "Radon"
    - name: twitter:url
      content: "https://radon-project.github.io/"

  generator: false

copyright: Build with love for the community © 2023-2024

plugins:
  - search

nav:
  - Overview: index.md
  - Installation: installation.md
  - Quick Start: quick-start.md
  - Documentation:
      - Data Types: data-types.md
      - Control Flow: control-flow.md
      - Loops: loops.md
      - Functions: functions.md
      - Classes: classes.md
      - Modules: modules.md
      - Input/Output: input-output.md
      # - Exceptions: exceptions.md
      # - File Handling: file-handling.md
      - Strings: strings.md
      - Arrays: arrays.md
      - Built-in Functions: built-in-functions.md

      - Language Reference: language-reference.md
      - Standard Library: standard-library.md
      - Tools: tools.md
  - Blog:
      Hello World: blog/hello-world.md
  - Contribution: contribution.md

markdown_extensions:
  - toc:
      permalink: true

  - markdown.extensions.codehilite:
      guess_lang: false

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - codehilite
  - extra
  - attr_list
  - md_in_html
  - abbr
  - admonition

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
